### ISSUE TITLE
Fatal error: Uncaught Error: Class 'R' not found

### ISSUE THREAD

**Issue by flik** [gabordemooij/redbean#537] opened 2017-01-28 06:45 UTC
I have installed redbean with composer and now getting error: Fatal error: Uncaught Error: Class 'R' not found

R::setup( 'mysql:host='.$dbc['host'].';dbname='.$dbc['database'],  $dbc['username'] ,  $dbc['password']  );

**Comment by cjaffar** [comment] 2017-01-28 12:34
wasted my time on this... also having that same error class R not found. shttttttt. wish i was allowed to swear here.

**Comment by cjaffar** [comment] 2017-01-28 12:35
don't waste pple's time with experimental stuff.



2017/01/28 14:29:28 [error] 3749#3749: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'R' not found in /var/www/phptest/public/index.php:18
Stack trace:
#0 {main}
  thrown in /var/www/phptest/public/index.php on line 18" while reading response header from upstream, client: 127.0.0.1, server: test.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "test.dev"

**Comment by r3wt** [comment] 2017-01-28 14:01
This is by design since composer uses namespaces to autoload. The fix for this is simple. Use `class_alias()` to alias `\RedBean\RedBean` as `R`. Im pretty sure this is mentioned in the docs under the using woth composer section. Dont criticize the package maintainer for your own lack of knowledge of composer and autoloading in general.

**Comment by r3wt** [comment] 2017-01-28 14:15
@flik This issue seems to trip up alot of new users of RedBean. I've opened a PR to address this in the readme, and cc'd the project maintainer and asked him to update the website as well. It will ultimately be up to him, since he's the BDFL of this project, for better or for worse.

**Comment by flik** [comment] 2017-01-29 12:46
@r3wt  I fixed this with this line of code on top of my php file. 
use RedBeanPHP\Facade as R;

where we want to use just use above line on top of file.

**Comment by flik** [comment] 2017-01-29 12:48
@cjaffar It is good Library just follow my solution. It will nice

**Comment by r3wt** [comment] 2017-01-29 20:59
`class_alias()` creates a global alias across all files, while `use` will only create alias for a single file. The class alias approach was also recommended to me long ago by the creator of this library. Im not sure what you hoped to achieve since I already provided a working solution, which is indeed the same approach used by the non composer version of this library.

**Closed** 2017-03-07 22:48 UTC

**Comment by emkaburu** [comment] 2017-06-05 22:33
@r3wt Where do you exactly add the class_alias('\RedBeanPHP\R','\R'); to get it working? Can't seem to quite figure it out?

**Comment by r3wt** [comment] 2017-06-06 01:19
@emkaburu here's an example of how i did it before. 

https://github.com/r3wt/phpBase/blob/master/App/Util/Database.php#L34
