### ISSUE TITLE
findOrCreate params

### ISSUE THREAD

**Issue by kirill-of-astra** [gabordemooij/redbean#642] opened 2018-04-28 11:08 UTC
// hi , i found strange behavior,  it maybe need fix or not : )

// $user, $product, $something - is Bean object

// this code everytime create new row in db table `rel`
$rel = R::findOrCreate('rel', ['user'=>$user, 'product' => $product, 'something' => $something]);

// this code working is correct
$rel = R::findOrCreate('rel', ['user_id' => $user->id, 'product_id' => $product->id, 'something_id' => $something->id]);

**Comment by Lynesth** [comment] 2018-04-28 11:16
Hello,

Yes, the find* functions do not work when passing bean objects as conditions, this isn't a bug as far as I know.
Nevertheless, this is something that could be done, I'm just not sure this is really needed... Let's wait for @gabordemooij 's answer on this matter.

Lyn.

**Comment by gabordemooij** [comment] 2018-04-29 11:32
It's not a bug, it just had never been implemented. But it's a nice feature request.

**Comment by Lynesth** [comment] 2018-06-27 00:35
@kirill-of-astra Hey there !
Did you get to try the merged PR ? Does it fit your needs ?

@gabordemooij I think this can be closed unless the OP has something else to add.

**Closed** 2018-07-16 06:18 UTC
Labels: feature request (accepted), intake
