### ISSUE TITLE
Nuke control

### ISSUE THREAD

**Issue by rivets** [gabordemooij/redbean#692] opened 2018-12-13 15:27 UTC
This is a feature request rather than an issue. The real issue is users who don't understand.... I use RedBean as part of my teaching and a student managed to accidentally call nuke and delete their whole database. It would be nice for such teaching situations to have a switch that disables nuke to prevent that kind of disaster.

**Comment by Lynesth** [comment] 2018-12-14 02:31
Hey there,
Here are some ideas/notes for your issue (I don't know how you work so that might be a bit off - Do you provide Redbean to your students or do they get it themselves ?) :

- Automysqlbackup (or equivalent)
- `R::nuke()` only works in Fluid mode (but I guess you can't Freeze)
- `R::nuke()` actually calls `DROP TABLE` so you could remove that permission from the database user
- Extend the Facade yourself (ie `class RB extends \RedBeanPHP\Facade`) so you can redefine the `nuke` function and have your students use `RB` instead of `R` from now on
- You could also - if providing Redbean to your students - hack into the `nuke` function to return (ugly but eh...)

**Comment by gabordemooij** [comment] 2018-12-14 07:36
Interesting problem. Regarding the last option, hacking the nuke function,
we could add a script to the repository to do that automatically. Maybe
call it after one of the anti nuclear treaties? 😉

Op vr 14 dec. 2018 03:31 schreef Lynesth <notifications@github.com:

**Comment by gabordemooij** [comment] 2018-12-14 07:38
A backup function in RedBeanPHP might also be interesting, have to look
into that too.

Op vr 14 dec. 2018 08:36 schreef Gabor de Mooij <
gabordemooij@gaborsoftware.nl:

**Comment by marios88** [comment] 2018-12-14 07:44
Since you are teaching, you can even extend `$writer->wipeAll()` and still be able to use `R`
Have it throw an error like `You just tried to delete the whole database. In real life, you should have setup an automated backup system`

**Comment by Lynesth** [comment] 2018-12-21 13:55
The only thing you can do that can help is to provide your own repo of RedBean with handmade modifications that disables `R::nuke()` (It wouldn't completely erase risks, but I guess that's the best you could do).
If you can't or don't want to provide it to your students then I don't see how anything we do could help.

1 - Even if a switch is implemented, if your students don't turn it on, then they can still wipe the whole thing.
2 - Even if we add a script like @gabordemooij suggested, it's still up to your students to run it.
3 - In any case, what would prevent them from calling `R::exec("DROP TABLE table1;")` ?

Anyway I think it's a good (yet terrible, I know) experience for your student, as it makes them learn to backup their work and such, and I bet that specific student will never make the same mistake.

(English isn't my mothertongue so just to let you know that I'm not trying to sound patronizing or anything like that).

--------

@gabordemooij : Is `R::nuke()` actually used outside of the unit testing ? I mean, is there people that call it for real ? Maybe that's just something we could remove entirely since we can just call `$writer->wipeAll();`
Just an idea, though I'm not in favor of removing it.

**Comment by gabordemooij** [comment] 2018-12-22 15:08
@Lynesth we don't know for sure. R::nuke() is also useful for temporary SQLite databases.

@Lynesth  @rivets @marios88 Thank you all for the feedback. I propose the following:

I think I favour R::backup()/R::restore() - this is a nice feature regardless of 'nuke control'. I would love to offer my customers a backup feature with just one line of code and without relying on mysqldump. It will take some time to implement this properly for all database platforms but we'll get there. Also, I consider to add the R::backup somewhere in the tutorial/examples so that new users will be advised to backup their working database before experimenting with other features.

**Comment by marios88** [comment] 2018-12-23 10:52
I personally use R::nuke only when working with temp databases, and its pretty useful
ie very fast workflow to test changes made to the seed file

Its a nice feature that saves time. Still, i could see having to call `R::allowNuke()` before using it or a get an exception
`R::nuke() will DROP all the tables in your current database.As a failsafe, to use it, you must enable it, calling R::allowNuke() first`

-----

I only have enough experience with mysqldump, it gets the job done and is battle tested.
R::backup sounds nice but probably a feature i would not risk using on production.  
Also note, there might be tables not managed by redbean, on the same database

**Comment by gabordemooij** [comment] 2018-12-23 11:02
@marios88 Interesting, R::allowNuke() is by far the easiest solution, but the question is, what will it break?

**Comment by gabordemooij** [comment] 2018-12-23 11:12
Yet another idea might be to use a different setup() method called init() and use that on the homepage and in the examples. Init() would block nuke() by default as well as setting some other sane defaults that can differ per version. This might help to make backward incompatible changes in the future easier as well.

For new bees:
`R::init( 'mysql:host=localhost....', $user, $pass )`

Same as above
`R::init( 'mysql:host=localhost....', $user, $pass, 'beginner@latest')` 

Pin point feature set:
`R::init( 'mysql:host=localhost....', $user, $pass, 'expert@version-5.3' )` 


Test drive (same as R::setup())
`R::init()`

**Comment by marios88** [comment] 2018-12-29 09:19
> @marios88 Interesting, R::allowNuke() is by far the easiest solution, but the question is, what will it break?

All of the test suite for sure! and probably all the the environments that use disposable databases. Its a bold change for sure. I am not really sure its a useful feature as @Lynesth pointed out, you can just `R::exec("DROP TABLE table1;")`

You could instead implement a `R::blockNuke()/R::allowNuke()` and include it in the demo/example code
```
R::setup();
R::setAutoResolve( TRUE ); //optional
R::blockNuke(); //optional
```
---
> Yet another idea might be to use a different setup() method called init() and use that on the > Pin point feature set (do not activate features that have been added in later versions):
> `R::init( 'mysql:host=localhost....', $user, $pass, 'expert@version-5.3' )`

Sounds a bit complicated with high future maintenance, `R::setup` always gives you a working database with a full feature set, fine tuning and option selection should be left to the user

**Comment by Lynesth** [comment] 2018-12-29 09:54
I agree with @marios88 that `R::init()` sounds a bit complicated and a duplicate of `R::setup()`.
Also adding a `R::allowNuke()` would force everyone using `R::nuke()` to rewrite stuff to make it work (breaking BC).

Though adding a `R::allowNuke()` wouldn't fix anything either as people would need to call it to make it effective.

Anyway, both still wouldn't prevent people from wiping the database with a simple "DROP TABLE".

I think that this whole thing really isn't an issue and that it's not RedBean's role to take people by the hand that much. I mean, should we also prevent them from calling `R::wipe()`, `R:hunt()`, etc ?

**Comment by gabordemooij** [comment] 2019-01-04 10:13
Happy 2019 everyone. I agree with @Lynesth - I was not thinking about the other ways to mess up the database. Even worse: `rm -rf /` ?

So instead, may I suggest I just write an explicit warning on the CRUD page in the manual?

**Comment by rivets** [comment] 2019-01-08 10:03
> The only thing you can do that can help is to provide your own repo of RedBean with handmade modifications that disables `R::nuke()` (It wouldn't completely erase risks, but I guess that's the best you could do).

Then I need to keep it in sync with the real version. Not practical

> If you can't or don't want to provide it to your students then I don't see how anything we do could help.
> 
> 1 - Even if a switch is implemented, if your students don't turn it on, then they can still wipe the whole thing.
> 2 - Even if we add a script like @gabordemooij suggested, it's still up to your students to run it.

The students are given a framework. The database initialisation is under my control so the call to disallow nuking would be made by me not them. If they want to explicitly allow nuking and call it then that would be fine too - see next comment.

> 3 - In any case, what would prevent them from calling `R::exec("DROP TABLE table1;")` ?

Nothing, and if someone did this they would know what they were doing. My problem is that not one but two students this year called nuke when they meant to call wipe. I was looking for a safety net. if nuke were called "deleteAllTables" or something then that would also do. 

> Anyway I think it's a good (yet terrible, I know) experience for your student, as it makes them learn to backup their work and such, and I bet that specific student will never make the same mistake.

I wouldn't bet on it.

> @gabordemooij : Is `R::nuke()` actually used outside of the unit testing ? I mean, is there people that call it for real ? Maybe that's just something we could remove entirely since we can just call `$writer->wipeAll();`
> Just an idea, though I'm not in favor of removing it.

I do call it as part of my framework initialisation - this makes it very simple to reinstall the framework over an older version should I want to do that (and I do).

I am not against nuke, and in fact am in favour of it, I just wanted to fence it in a little :-)

L.

**Comment by Lynesth** [comment] 2019-01-08 10:51
@rivets what about using namespace to create your own class R then ?

```php
namespace YourFramework;
include_once 'rb.php';

class R extends \RedBeanPHP\Facade {
    public static function nuke() {
        throw new Exception('Hey, you tried to call nuke ! Be careful ;)');
    }
}
```

**Comment by gabordemooij** [comment] 2019-01-21 18:55
Okay

I have added R::noNuke() just in case somebody wants to turn off the nuke() feature.

I also added R::useFeatureSet().

R::useFeatureSet( 'novice/latest' )

will do:

R::setAutoResolve( TRUE );
R::noNuke( TRUE );


Other combinations/suggestions are welcome...

**Comment by rivets** [comment] 2019-02-19 13:20
Excellent! Much appreciated!

**Closed** 2019-04-12 18:18 UTC
Labels: 5.3, closing soon..., feature request (accepted), researching, resolved
